# Generated by Django 5.0.6 on 2024-07-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.BigIntegerField(blank=True, help_text='введите ID Telegram для оповещения', null=True, unique=True, verbose_name='ID Telegram'),
        ),
    ]
