# Generated by Django 5.0.6 on 2024-06-27 11:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='введите место выполнения привычки', max_length=225, verbose_name='место выполнения привычки')),
                ('time_start_habits', models.TimeField(verbose_name='время начала привычки')),
                ('action', models.CharField(help_text='введите действие которое выполняет привычка', max_length=150, verbose_name='действие привычки')),
                ('pleasant_habit', models.BooleanField(default=False, help_text='выберите, если привычку можно привязать к полезной привычке', verbose_name='признак приятной привычки')),
                ('linked_habit', models.CharField(blank=True, help_text='введите связанную привычку для полезных привычек', max_length=225, null=True, verbose_name='связанная привычка')),
                ('reminder_period_days', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='период напоминания в днях')),
                ('award', models.CharField(blank=True, help_text='введите вознаграждение', max_length=150, null=True, verbose_name='вознаграждение')),
                ('time_perform', models.TimeField(help_text='введите время на выполнение не более 120 секунд', verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, help_text='выберите, если хотите публиковать привычку', verbose_name='признак публичной привычки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец привычки')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
