# Generated by Django 5.0.6 on 2024-07-02 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_reminder_frequency_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='linked_habit',
            field=models.ForeignKey(blank=True, help_text='введите связанную привычку для полезных привычек', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='pleasant_habit',
            field=models.BooleanField(default=False, help_text='выберите, если привычку можно отнести к полезной привычке', verbose_name='признак приятной привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reminder_frequency_days',
            field=models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], help_text='выберите день недели для напоминаний о выполнении привычки', verbose_name='периодичность выполнения привычки в днях'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_perform',
            field=models.TimeField(help_text='введите время на выполнение не более 120 секунд в формате ЧЧ:ММ:СС', verbose_name='время на выполнение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_start_habits',
            field=models.TimeField(help_text='формат заполнения: ЧЧ:ММ:СС', verbose_name='время начала привычки'),
        ),
    ]
