# Generated by Django 5.0.6 on 2024-07-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_linked_habit_alter_habit_pleasant_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='pleasant_habit',
            field=models.BooleanField(default=False, help_text='выберите, если привычку можно отнести к приятной привычке', verbose_name='признак приятной привычки'),
        ),
    ]
